### PR TITLE
Add lease model

### PR DESCRIPTION
**Pull request by jeremyrader**
updated lease model and property model. fixes #167 in dwellingly-app

### CODE REVIEW

**Review by htharker42 — CHANGES_REQUESTED** [review]
Looks good so far. Please expose the lease resource  to the endpoints /lease, /leases  in app.py so we can test the endpoints.

**Comment by zfregin** [comment]
Looks good, I noticed the Occupants field got declared twice on the LeaseModel, so I got rid of the 2nd one.

I tested both `/lease` and `/lease/id` endpoints in Postman and everything checked out. One thing I noted is that the Occupants/Tenants data is repeated several times within the data body, but I'm assuming it was intentionally denormalized.

`{
    "id": 1,
    "name": "Lease 1",
    "propertyID": {
        "id": 1,
        "name": "test1",
        "address": "123 NE FLanders St",
        "unit": "5",
        "city": "Portland",
        "state": "OR",
        "zipcode": "97207",
        "propertyManager": 5,
        "tenants": 3,
        "dateAdded": "2020-04-12",
        "archived": false
    },
    "landlordID": {
        "id": 1,
        "firstName": "user1",
        "lastName": "tester",
        "email": "user1@dwellingly.org",
        "role": "admin",
        "archived": false
    },
    "tenantID": {
        "id": 1,
        "firstName": "Renty",
        "lastName": "McRenter",
        "phone": "800-RENT-ALOT",
        "propertyID": 1,
        "propertyName": "test1",
        "propertyAddress": "123 NE FLanders St",
        "propertyTenants": 3,
        "staff": [
            {
                "id": 1,
                "firstName": "user1",
                "lastName": "tester",
                "email": "user1@dwellingly.org",
                "role": "admin",
                "archived": false
            },
            {
                "id": 2,
                "firstName": "user2",
                "lastName": "tester",
                "email": "user2@dwellingly.org",
                "role": "admin",
                "archived": false
            }
        ]
    },
    "dateTimeStart": "08/02/2020 01:14:08",
    "dateTimeEnd": "08/02/2021 01:14:08",
    "dateUpdated": "08/02/2020 01:14:08",
    "occupants": 3
}`

**Review by zfregin — DISMISSED** [review]
Everything looks good in Postman, see my comment for notes

**Review by htharker42 — DISMISSED** [review]

**Comment by Chris-Boe** [comment]
Looks like we just gotta resolve merge conflicts

**Review by htharker42 — DISMISSED** [review]

**Review by htharker42 — APPROVED** [review]
Review passed

**Pull request merged**
