### PR TITLE
remove home resource

### LINKED ISSUE #400: Remove the Home resource
**Purpose**
Remove the Home resource. It is no longer needed.

### PR DESCRIPTION
**Pull request by sidmirza4**
### What issue is this solving?

Closes codeforpdx/dwellingly-app/issues/400

### Any helpful knowledge/context for the reviewer?
Is a re-seeding of the database necessary?
Any new dependencies to install?
Any special requirements to test?

### Please make sure you've attempted to meet the following coding standards
- [ ] Code builds successfully
- [ ] Code has been tested and does not produce errors
- [ ] Code is readable and formatted
- [ ] There isn't any unnecessary commented-out code

### CODE REVIEW

**Comment by NickSchimek** [comment]
@sidmirza4 The build is failing. To fix this could you pull the latest changes from development and rebase this PR?

**Comment by sidmirza4** [comment]
yeah sure

**Comment by sidmirza4** [comment]
I am new to this PR and all, would you please guide me , so that I do everything correctly
Thanks
Sid

**Comment by NickSchimek** [comment]
@sidmirza4 sure! Try running these commands: You shouldn't run into any issues, but if you do then you can let me know, or google it.
```
git remote add upstream https://github.com/codeforpdx/dwellinglybackend
git checkout development
git pull upstream development
git checkout 400-remove-home-resource
git rebase development
git push
```

This adds a new remote upstream
pull down the latest changes from upstream onto your development branch
and then rebases your branch on top of the latest changes

**Comment by sidmirza4** [comment]
when I run 'git pull upstream development' , I get this error: 
fatal: refusing to merge unrelated histories

**Comment by sidmirza4** [comment]
already did it.
Thanks
Sid

**Comment by sidmirza4** [comment]
I have updated the PR, please review and let me know

**Review by NickSchimek — APPROVED** [review]
Thank you for taking care of this!

**Pull request merged**
