### PR TITLE
Pytest

### PR DESCRIPTION
**Pull request by DaveTrost**
- [x] Install and setup pytest and coverage tools
- [x] write basic unit and integration tests
- [x] use the coverage tool to get to 100% code coverage from the tests for user routes

### CODE REVIEW

**Comment by DaveTrost** [comment]
This PR should also close issue [#80](https://github.com/codeforpdx/dwellingly-app/issues/80)

**Review by KentShikama — COMMENTED** [review]
Note for RecordSponge we ended up using `pytest-cov`. `pipenv run pytest --cov=<module_name>` will dump the coverage report at the end of the test runs. It looks like the following:

```
----------- coverage: platform linux, python 3.7.7-final-0 -----------
Name                                                         Stmts   Miss  Cover
--------------------------------------------------------------------------------
expungeservice/__init__.py                                       6      0   100%
expungeservice/app.py                                           20      0   100%
expungeservice/charge_classifier.py                            250      3    99%
expungeservice/charge_creator.py                                39      0   100%
expungeservice/config.py                                        17      0   100%
...
```

**Comment by DaveTrost** [comment]
@KentShikama, it looks like the pytest-cov library is a superset of the coverage library. I wonder what advantages of pytest-cov are considered most useful by the RecordSponge team (subprocess support, xdist support, consistent sys.path behavior)? 

I tried but so far I've been unable to run pytest-cov. The command `pipenv run pytest --cov=.` yields the following errors for me:
```
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --cov=.
  inifile: None
  rootdir: C:\Users\davet\open-source\dwellinglybackend
```

**Comment by KentShikama** [comment]
@DaveTrost Have you tried `pipenv run pytest --cov .`? 

Edit: The advantage is that it "just works". We didn't really look into how those 3 additional features benefit us. I guess `coverage run -m pytest ...` mostly "just works" too. I didn't know you could just run it as one command before. As a fairly minor point, I like how `pipenv run pytest --cov` is clearer about how you're running pytest (with some options) rather than `coverage run -m pytest ...` which makes it feel like `coverage` is the main program running.

**Comment by DaveTrost** [comment]
I got pytest-cov to work. `pipenv install pytest-cov` ... Oh boy do I feel like a noob!! 🤦

@KentShikama - thanks for the suggestion. I think it is nice to have both tools available. The pytest-cov module provides a basic reporting of coverage. The html report from the coverage module is a high level of detail to see exactly which lines of code were not sensitized by the test suite. Of course the html report requires a bit more overhead, but I think it's a useful tool for anyone trying to push their test coverage to 100%.

I updated the PR based on your suggestions.

**Review by htharker42 — APPROVED** [review]

**Pull request merged**
