### PR TITLE
Emergency contacts

### PR DESCRIPTION
**Pull request by DaveTrost**
- [x] create emergency contact model 
- [x] create contact number model. There is a one to many relationship between emergency contacts and contact numbers
- [x] connect an emergency contacts resource
- [x] create emergencycontacts endpoint 
  - [x] get -> returns all emergency contacts
  - [x] post -> creates a new emergency contact
  - [x] put -> modifies an emergency contact
  - [x] delete -> removes an emergency contact
- [x] update the README

### CODE REVIEW

**Comment by DaveTrost** [comment]
The development branch was updated so it was necessary to rebase this branch on development.

**Review by Chris-Boe — CHANGES_REQUESTED** [review]
Looks like this PR also has Kent's commits like the front end PR did

**Comment by DaveTrost** [comment]
@Chris-Boe - good catch about the additional baggage in this PR. I'm having to learn a few more tricks in Git these days. Didn't know you could do this kind of stuff!
Should be fixed now.

**Review by Chris-Boe — APPROVED** [review]

**Comment by Chris-Boe** [comment]
Nice! Looks great with the frontend!

**Pull request merged**
