### PR TITLE
641 update notes terminology

### LINKED ISSUE #641: Update terminology in notes model
Update notes model to replace `ticketid` with `ticket_id` and `userid` with `author_id`
Other files may also need to be changed.

### PR DESCRIPTION
**Pull request by Protopaco**
## Description

Updates NotesModel variables ticketid to ticket_id and userid to user_id as well as the other files that access those variables.  
Thanks for pointing this out, its been bothering me!

### What issue is this solving?

Closes codeforpdx/dwellingly-app/issues/641

### CODE REVIEW

**Review by aedwardg — DISMISSED** [review]
@Protopaco, this looks good to go.  However, it looks like you already incorporated the changes from #283 into this one even though they weren't needed here.  Because of that, you _might_ have to do a `git pull --rebase origin development` once #283 is merged in.

**Comment by aedwardg** [comment]
@NickSchimek, this one should be merged in **after** #283.

**Comment by NickSchimek** [comment]
Good catch, that extra commit can be removed with an interactive rebase. Is that the reason your suggesting to merge this after the other PR, because it includes that extra commit?

**Comment by aedwardg** [comment]
Right, since commit 980e906 is the one that solves #283's issue, I wanted to make sure this PR wasn't accidentally merged before #283 while it still contained that commit.  If it was, both this PR and that one wouldn't be doing what they claim to be doing.
Just trying to keep our git history squeaky clean 😄

**Comment by Protopaco** [comment]
@aedwardg Thank you for catching this!  I did an interactive rebase, and I believe I removed the unnecessary commit.   Please let me know if I missed anything else.

**Review by NickSchimek — APPROVED** [review]
Thanks!

**Pull request merged**
