### PR TITLE
Add more settings to .vscode/settings.json

### PR DESCRIPTION
**Pull request by gussmith23**
### What issue is this solving?
No issue for this one.
I discussed this in standup: I switched to vscode, and my editor automatically added some settings. They seem pretty basic, would love to hear peoples' opinions.

### Any helpful knowledge/context for the reviewer?
Is a re-seeding of the database necessary? NO
Any new dependencies to install? NO
Any special requirements to test? NO

### Please make sure you've attempted to meet the following coding standards
- [ ] Code builds successfully
- [ ] Code has been tested and does not produce errors
- [ ] Code is readable and formatted
- [ ] There isn't any unnecessary commented-out code

### CODE REVIEW

**Review by NickSchimek — APPROVED** [review]
I don't think we should be committing this file, I believe I removed it once, but it got added back. However, since I don't use VS Code it doesn't affect me 😉

**Comment by aedwardg** [comment]
I wonder if there is a better way to include these settings for VS Code users.  I've always put the `.vscode` folder in the `.gitignore` because VS Code will append things like the absolute path of your Python version into `settings.json` without telling you and you don't want to commit/push that to the repo.

Maybe we could add in something similar to the `.env.example` where newcomers can just copy those settings into their own `settings.json`, but have the `.vscode` folder in `.gitignore` to prevent accidental changes from being pushed.

**Comment by gussmith23** [comment]
This would be fine with me! Ignoring the .vscode dir would be just as good
for my needs.

**Comment by NickSchimek** [comment]
Yes, this should be in the `.gitignore` - I had added it there once before it, but it keeps making its way back in for some reason.  Maybe I didn't gitignore correctly, and since I don't use vscode I didn't notice it. I'd be happy to accept a pull request.

**Pull request merged**
