### PR TITLE
added unit test for notes model

### LINKED ISSUE #412: Create Unit tests for notes model
**Purpose**
public methods should have tests

**Acceptance Criteria**
- [ ] Add the BaseInterfaceTest to `tests/unit/test_note.py` and create unit tests for all public methods. see [this commit](https://github.com/codeforpdx/dwellinglybackend/blob/31610de13449c002d2394bfa7b2e48a8c12e5b1e/tests/unit/test_lease.py) for an example.

### PR DESCRIPTION
**Pull request by yunnie**
### What issue is this solving?

Closes codeforpdx/dwellingly-app/issues/412

### Any helpful knowledge/context for the reviewer?
Is a re-seeding of the database necessary? No
Any new dependencies to install? No
Any special requirements to test? No

### Please make sure you've attempted to meet the following coding standards
- [x ] Code builds successfully
- [x ] Code has been tested and does not produce errors
- [x ] Code is readable and formatted
- [x ] There isn't any unnecessary commented-out code

### Other comments
The notes model contains a ```json``` method, so I added a test for the method

### CODE REVIEW

**Review by NickSchimek — APPROVED** [review]
Thanks for doing this! It looks great.

**Review by NickSchimek — CHANGES_REQUESTED** [review]
Now that the pre-commit hook PR has been merged. Can you rebase on top of the development branch? As there are some formatting issues that should be fixed. I could do this too if your not sure how.

**Comment by NickSchimek** [comment]
Sorry, I closed and reopened so that the build would be ran with the new CI configuration. The new config includes the pre-commit checks.

**Comment by yunnie** [comment]
I rebased, and I think everything passes...

**Review by NickSchimek — APPROVED** [review]
Thank you @yunnie Sorry to put you through extra trouble.

**Pull request merged**
